package template

func Code(name string) string {
	return `
package vo

// INVALID_REQUEST_PARAMETERS 无效的请求参数
const INVALID_REQUEST_PARAMETERS = "INVALID_REQUEST_PARAMETERS"

// SUCCESS 成功
const SUCCESS = "SUCCESS"

// FAILED 失败
const FAILED = "FAILED"

// CREATION_FAILED 创建失败
const CREATION_FAILED = "CREATION_FAILED"

// CREATION_SUCCESS 创建成功
const CREATION_SUCCESS = "CREATION_SUCCESS"

// UPDATE_FAILED 更新失败
const UPDATE_FAILED = "UPDATE_FAILED"

// UPDATE_SUCCESS 更新成功
const UPDATE_SUCCESS = "UPDATE_SUCCESS"

// DELETE_FAILED 删除失败
const DELETE_FAILED = "DELETE_FAILED"

// DELETE_SUCCESS 删除成功
const DELETE_SUCCESS = "DELETE_SUCCESS"

`

}
